name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  install:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run install
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm install
      
  ############## Linter Job ###############
  linter:
    needs: install
    name: linter 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Linter ESLint
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm run lint

  ############################### Formatter (Prettier) npm run prettier ################
  formatter:
    needs: linter
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:  Formatter Prettier
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm run prettier

  ################################# Test (Jest) CI=true npm run test ##################
  test:
    needs: formatter
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test Jest
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm run test

  ################################# Build npm run build ##################
  build:
    needs: test
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: test Jest
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm run build 
